### ISSUE TITLE
referencing cloning as forking

### ISSUE THREAD

**Issue by DanielLitvak** [devopsloft/training#54]
In lines https://github.com/devopsloft/training/blame/9a3466a0b2de64cf5d7bc289367413b64ee6c014/git/README.md#L7-L15
there is a reference to the clone action but the meaning is for the fork action.
As cloning someone else's repo is not best practice the text should tell to fork the repo and then clone it.

**Comment by lmilbaum** [comment]
@DanielLitvak Agree. Are you going to fix it?
